name: release-firefox

on:
  workflow_dispatch:

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: set up node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: build project
        run: make build

      - id: pack-extension-dir
        uses: cardinalby/webext-buildtools-pack-extension-dir-action@v1
        with:
          extensionDir: ./
          zipFilePath: fangen.zip

      - name: sign fangen for firefox
        uses: kewisch/action-web-ext@v1
        with:
          cmd: sign
          source: fangen.zip
          artifacts: ./dist
          channel: unlisted
          apiKey: ${{ secrets.AMO_JWT_ISSUER }}
          apiSecret: ${{ secrets.AMO_JWT_SECRET }}

      - name: upload xpi artifact
        uses: actions/upload-artifact@v4
        with:
          name: fangen.xpi
          path: dist/*.xpi
