name: release-github

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
      - v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+

jobs:
  build-packed-crx-file:
    name: build
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: assert tag
        uses: zaryo/release-action/match-version@b58fb98ef2d7d01f9150011ef2fe28b6076c21af
        with:
          source: browser_extension_manifest

      - name: set up node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: build project
        run: make build

      - id: packExtensionDir
        uses: cardinalby/webext-buildtools-pack-extension-dir-action@v1
        with:
          extensionDir: ./
          zipFilePath: fangen.zip

      - name: upload zip artifact
        uses: actions/upload-artifact@v4
        with:
          name: fangen.zip
          path: fangen.zip

  release:
    name: release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - id: release-version
        uses: intentee/release-action/release-tag-to-version@8125f727e97f72bfef24299d7c6d3217af1453bc
        with:
          release-tag: "${{ github.ref_name }}"

      - name: download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: true

      - name: create github release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/*
          name: ${{ steps.release-version.outputs.name }}
          body: ${{ steps.release-version.outputs.description }}
          prerelease: ${{ steps.release-version.outputs.type == 'PRE_RELEASE' }}
          tag_name: ${{ github.ref }}
